---
  - name : "Installations"
    hosts : localhost
    connection : local

    tasks :

      - name : "Install mysql 5.7"
        apt:
          name : "mysql-server-5.7"
          update_cache : yes
          state : "latest"
        become : yes

      - name : "Install php"
        apt:
          name : "php"
          update_cache : yes
          state : "latest"
        become : yes